### ISSUE TITLE
설치하면 다 깨져서 나옵니다.

### ISSUE THREAD

**Issue by Gwangtori** [openNAMU/openNAMU-Skin-Liberty#10]
![image](https://user-images.githubusercontent.com/64156915/122563123-cab13580-d07e-11eb-95dd-f717411511f4.png)

버전은 v3.2.0-stable-13 (beta-60) (dev-2021-03-29-01)이고, 컴퓨터(엣지), 폰(웨일) 둘다 깨져서 나오네요...

**Comment by surplus-dev** [comment]
사용법이 틀렸습니다

**Comment by Gwangtori** [comment]
폴더 이름을 'liberty'로 바꾸니까 해결됐네요. 확인 감사합니다! 오늘도 좋은 하루 보내세요 ㅎㅎ
