### ISSUE TITLE
업데이트 후 오류

### ISSUE THREAD

**Issue by cuprevenge** [openNAMU/openNAMU-Skin-Liberty#13]
업데이트 후 아이콘들이 나오지 않고 최근 편집/토론이 작동하지 않습니다.

**Comment by surplus-dev** [comment]
이전에 CDN으로 변경한 부분 전부 롤백 했습니다

**Comment by cuprevenge** [comment]
이번엔 css가 전부 무너집니다.

**Comment by surplus-dev** [comment]
캐시 초기화 후에도 동일한가요?

**Comment by cuprevenge** [comment]
> 캐시 초기화 후에도 동일한가요?

네

**Comment by cuprevenge** [comment]
![image](https://user-images.githubusercontent.com/52319594/141465377-87447c16-abb3-4a6c-9212-3014c1a034a5.png)

콘솔 오류 메시지

**Comment by surplus-dev** [comment]
본 에러는 HTTPS에서 HTTP 사이트를 요청할 때 뜨는 에러인데... 어... 이 스킨상에서 HTTP를 요구하는 파트가 없습니다

혹시 좀 더 자세한 에러 로그 없나요?

**Comment by cuprevenge** [comment]
![image](https://user-images.githubusercontent.com/52319594/141652308-31a57abc-490d-48c0-a01f-40170b64d12d.png)

포트(domain:3000)로 접근하면 이게 추가로 뜨긴 합니다.

**Comment by surplus-dev** [comment]
이전 리버티에선 이런 버그가 없었나요?

**Comment by cuprevenge** [comment]
v1.1.6까지는 문제가 없습니다.

**Comment by cuprevenge** [comment]
별로 상관없는 것 같지만 git pull 시 2개만 %가 이렇게 나오는 것도 있긴 하네요

rename css/style.css => static/css/wiki.css (79%)
rename {js => static/js}/skin_set.js (95%)

**Comment by surplus-dev** [comment]
재 점검 예정

지금 다시 v1.1.6을 써도 해당 문제가 발생하지 않나요?

**Comment by cuprevenge** [comment]
> 재 점검 예정
> 
> 지금 다시 v1.1.6을 써도 해당 문제가 발생하지 않나요?

v1.1.7, v1.1.8 업데이트 시 문제가 발생해 v1.1.6으로 회귀(git reset --hard 45abf67c461ac932bb849f33c98a400b03be14b6)해서 유지하고 있습니다.

**Comment by surplus-dev** [comment]
그냥 1.1.6 소스에다가 기능만 추가하는 형식으로 수정 예정

**Comment by surplus-dev** [comment]
v1.1.6 기반 소스로 다시 만들었습니다 v1.1.9

**Comment by cuprevenge** [comment]
![image](https://user-images.githubusercontent.com/52319594/142765038-c21b4bcb-eb1a-45c0-af57-b48a0078e5f9.png)
![image](https://user-images.githubusercontent.com/52319594/142765243-e7332af6-4011-4a38-9c52-d811383a8ae0.png)

왜 이게 mixed-content로 취급되는 걸까요..
