### ISSUE TITLE
모바일 테이블 css

### ISSUE THREAD

**Issue by cuprevenge** [openNAMU/openNAMU-Skin-Liberty#15]
모바일에서 왼쪽이 잘리는 현상이 있습니다.

예시 문서 : https://onemindwiki.kr/w/%EC%A7%80%EC%B0%AC%EC%9C%84%ED%82%A4

![image](https://user-images.githubusercontent.com/52319594/154001430-37682ac3-e92e-4fd0-960f-c42b492ff5c4.png)

**Comment by surplus-dev** [comment]
렌더러 문제라서 렌더러 상에서 해결 했습니다
