### ISSUE TITLE
표 테두리, 점프 버튼 UI 관련 (브라우저 표준 관련 문제)

### ISSUE THREAD

**Issue by Gwangtori** [openNAMU/openNAMU-Skin-Liberty#17]
![FFA85FEC-2C78-4E40-9069-F1A94FB2C6BE](https://user-images.githubusercontent.com/64156915/199279292-f4b389e9-0c99-45e6-b82f-5a7fd689c753.jpeg)

## 접속 기기
- 기기: iPhone 12
- 세부 정보: iOS 16.2, 엣지 브라우저

## 내용
1. 표 테두리가 보이지 않아요. 
2. 점프 버튼의 색과 버튼 간의 간격이 떨어져 있어요.

**Comment by Gwangtori** [comment]
표 테두리가 안 보이는 이슈는 Ringo 스킨과 Tenshi에서도 발생하네요...

**Comment by surplus-dev** [comment]
사파리에서는 0.5px border을 인식 못하나보네요

반대로 크롬에서는 1px border이 2px처럼 보이는 문제가 있고요...

브라우저 인식해서 조절하는 걸로 해보겠습니다

**Comment by surplus-dev** [comment]
1. 표 테두리는 main.css 상에서 조절과 관련 있기 때문에 본 레포로 이전하겠습니다
2. 점프 버튼 문제는 v1.1.12에서 수정되었을 것이라고... 기대하고 있습니다(?) iOS 환경이 없어서 테스트가 불가능 합니다

**Comment by Gwangtori** [comment]
점프 버튼 문제 해결되었어요 :)
