### ISSUE TITLE
스킨 적용 시 깨집니다.

### ISSUE THREAD

**Issue by EricKim27** [openNAMU/openNAMU-Skin-Liberty#25]
![Screenshot_20231112_110704_Samsung Internet.jpg](https://github.com/openNAMU/openNAMU-Skin-Liberty/assets/92709321/3c6c1a25-9b9c-4811-9ebb-8d2e934a37f1)

폴더의 이름을 liberty로 바꿨음에도 깨집니다. 참고로 apache 서버에 리버스 프록시로 실행하고 있습니다.

**Comment by Gwangtori** [comment]
엔진이 스킨 파일을 못 읽어오는 것 같습니다
- 엔진을 켜놓은 상태에서 스킨을 다운로드 하셨다면 엔진을 재시작 해보세요.
- 스킨 파일의 권한들을 올려보세요.
- 캐시 문제일 수 있습니다. 브라우저의 캐시나 이머전시 툴을 통해 엔진의 캐시를 지워보세요.

**Comment by surplus-dev** [comment]
해결 되었나요?

**Comment by EricKim27** [comment]
권한 설정을 변경하니 해결되었습니다. 감사합니다.
