### ISSUE TITLE
CSS 파일 깨짐

### ISSUE THREAD

**Issue by EricKim27** [openNAMU/openNAMU-Skin-Liberty#26]
어제 css 파일이 로딩이 안 되다가 권한 설정을 바꾸고 해결이 되었는데, 오픈나무 엔진을 재시작하니 다시 css 파일이 깨집니다. 다시 다운받고, 이름 바꾸고, 권한 설정을 바꿔도 해결이 되지 않습니다. 엔진을 시작할 때 db 백업 에러라고 뜨는데, 이게 문제인걸까요?

**Comment by surplus-dev** [comment]
sudo로 실행해도 그런가요? 백업 에러도 오픈나무 실행 권한 자체가 낮기 때문에 새로운 파일을 write 못해서 생기는 문제가 아닐까 생각하고 있습니다

**Comment by EricKim27** [comment]
제가 오픈나무를 systemd 서비스로 실행하고 있는데, 그렇게 해도 문제가 발생합니다.

**Comment by EricKim27** [comment]
Sudo로 실행을 해보니까 css 파일이 로딩되네요

**Comment by surplus-dev** [comment]
그러면 여전히 오픈나무 실행 권한 문제인 것 같습니다

**Comment by EricKim27** [comment]
한번 sudo로 실행하고 서비스를 실행시키니 다시 되네요. 뭐가 문제인지는 아직 잘 모르겠네요.
