### ISSUE TITLE
구조상 문제 해결

### ISSUE THREAD

**Issue by ghost** [openNAMU/openNAMU-Skin-Liberty#28]
<li class="nav-item">
                        <a class="nav-link" href="/recent_discuss"><span class="fa fa-comments"></span><span class="hide-title">{{'recent_discussion'|load_lang}}</span></a>
                    </li>

해당 코드를 통해 오픈나무에서 /recent_discuss로 연결되면 닫힌 토론, 열린 토론, 중지된 토론이 마구잡이로 나타나기 때문에 아래와 같은 개선이 필요합니다.

   <li class="nav-item">
                        <a class="nav-link" href="/recent_discuss/1/open"><span class="fa fa-comments"></span><span class="hide-title">{{'recent_discussion'|load_lang}}</span></a>
                    </li>

**Comment by surplus-dev** [comment]
뭔 말인 지 모르겠습니다

**Comment by surplus-dev** [comment]
혹시 최근 토론에서 닫힌 토론 중지된 토론이 전부 나타나는 것을 이야기 하는 거라면 그건 의도된 사안입니다

**Comment by ghost** [comment]
? 아 그런가요?

**Comment by surplus-dev** [comment]
네

**Comment by ghost** [comment]
그러면 제가 알아서 개조해서 써도 될까요?

**Comment by surplus-dev** [comment]
네 저작권 조항을 준수하면 맘대로 써도 됩니다
